version: '2'

services:
  proxy:
    build: ./src
    command: bash -c "./run.sh"
    volumes:
      - ./logs:/var/log/erss
      - ./src:/app
    ports:
      - "12345:12345"
    tty: true


volumes:
  data-volume:
